// Generated by gencpp from file common_msgs/Lanes.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_LANES_H
#define COMMON_MSGS_MESSAGE_LANES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <common_msgs/Lane.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct Lanes_
{
  typedef Lanes_<ContainerAllocator> Type;

  Lanes_()
    : header()
    , num(0)
    , lanes()  {
    }
  Lanes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num(0)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_type;
  _num_type num;

   typedef std::vector< ::common_msgs::Lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::common_msgs::Lane_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;





  typedef boost::shared_ptr< ::common_msgs::Lanes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::Lanes_<ContainerAllocator> const> ConstPtr;

}; // struct Lanes_

typedef ::common_msgs::Lanes_<std::allocator<void> > Lanes;

typedef boost::shared_ptr< ::common_msgs::Lanes > LanesPtr;
typedef boost::shared_ptr< ::common_msgs::Lanes const> LanesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::Lanes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::Lanes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::Lanes_<ContainerAllocator1> & lhs, const ::common_msgs::Lanes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num == rhs.num &&
    lhs.lanes == rhs.lanes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::Lanes_<ContainerAllocator1> & lhs, const ::common_msgs::Lanes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Lanes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Lanes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Lanes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Lanes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Lanes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7338c9f7da570ebf95e5bc3ebf71638";
  }

  static const char* value(const ::common_msgs::Lanes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7338c9f7da570ebULL;
  static const uint64_t static_value2 = 0xf95e5bc3ebf71638ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/Lanes";
  }

  static const char* value(const ::common_msgs::Lanes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::Lanes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header  header\n"
"int32 num                                            #车道线数量\n"
"Lane[] lanes                                         #车道线描述\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: common_msgs/Lane\n"
"# 单条车道线描述\n"
"uint8 lane_idx #车道线ID\n"
"float32 c_0    #车道线参数C0\n"
"float32 c_1    #车道线参数C1\n"
"float32 c_2    #车道线参数C2\n"
"float32 c_3    #车道线参数C3\n"
;
  }

  static const char* value(const ::common_msgs::Lanes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::Lanes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lanes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::Lanes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::Lanes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::common_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_LANES_H
