// Generated by gencpp from file common_msgs/objects.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_OBJECTS_H
#define COMMON_MSGS_MESSAGE_OBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <common_msgs/object.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct objects_
{
  typedef objects_<ContainerAllocator> Type;

  objects_()
    : header()
    , num(0)
    , objects()  {
    }
  objects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num(0)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_type;
  _num_type num;

   typedef std::vector< ::common_msgs::object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::common_msgs::object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::common_msgs::objects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::objects_<ContainerAllocator> const> ConstPtr;

}; // struct objects_

typedef ::common_msgs::objects_<std::allocator<void> > objects;

typedef boost::shared_ptr< ::common_msgs::objects > objectsPtr;
typedef boost::shared_ptr< ::common_msgs::objects const> objectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::objects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::objects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_msgs::objects_<ContainerAllocator1> & lhs, const ::common_msgs::objects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.num == rhs.num &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_msgs::objects_<ContainerAllocator1> & lhs, const ::common_msgs::objects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_msgs::objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::objects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::objects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::objects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::objects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::objects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed31e297e0290d75c5fb045bbeea74cb";
  }

  static const char* value(const ::common_msgs::objects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed31e297e0290d75ULL;
  static const uint64_t static_value2 = 0xc5fb045bbeea74cbULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/objects";
  }

  static const char* value(const ::common_msgs::objects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::objects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header  header\n"
"int32 num                                #目标数量\n"
"object[] objects                         #目标描述\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: common_msgs/object\n"
"uint32 Object_ID                        #目标的ID编号\n"
"float32 Object_DistLong                 #目标的纵向距离\n"
"float32 Object_DistLat                  #目标的横向距离\n"
"float32 Object_VrelLong                 #目标的纵向相对速度\n"
"float32 Object_VrelLat                  #目标的横向相对速度\n"
"uint32 Object_DynProp                   #目标的运动状态\n"
"float32 Object_ArelLong                 #目标的纵向加速度\n"
"float32 Object_ArelLat                  #目标的横向加速度\n"
"uint32 Object_Class                     #目标的分类\n"
"float32 Object_Length                   #目标的长度\n"
"float32 Object_Width                    #目标的宽度\n"
"uint32 Object_ProbOfExist               #目标置信度\n"
;
  }

  static const char* value(const ::common_msgs::objects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::objects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::objects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::objects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::common_msgs::object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_OBJECTS_H
