std_msgs/Header  header
float32 V_VehSpdX               #本车X向车速
float32 V_VehSpdY               #本车Y向车速
float32 V_VehAccelX             #本车纵向加速度
float32 V_VehAccelY             #本车横向加速度
float32 V_VehPosYaw             #本车航向角
float32 V_VehPosX               #本车X向坐标
float32 V_VehPosY               #本车Y向坐标
float32 V_VehPosRoll            #本车Roll
float32 V_VehPosPitch           #本车Pitch
uint32 GearLevPos               #底盘反馈当前档位
#float32 BrakePedal              #本车制动踏板开度
#float32 ThrottlePedal           #本车油门踏板开度
#float32 SteeringAngle           #本车方向盘转角

