# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from common_msgs/Vehicle_Feedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Vehicle_Feedback(genpy.Message):
  _md5sum = "9dae5a81ecfdc3c6e7aac43803325361"
  _type = "common_msgs/Vehicle_Feedback"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header  header
float32 V_VehSpdX               #本车X向车速
float32 V_VehSpdY               #本车Y向车速
float32 V_VehAccelX             #本车纵向加速度
float32 V_VehAccelY             #本车横向加速度
float32 V_VehPosYaw             #本车航向角
float32 V_VehPosX               #本车X向坐标
float32 V_VehPosY               #本车Y向坐标
float32 V_VehPosRoll            #本车Roll
float32 V_VehPosPitch           #本车Pitch
uint32 GearLevPos               #底盘反馈当前档位
#float32 BrakePedal              #本车制动踏板开度
#float32 ThrottlePedal           #本车油门踏板开度
#float32 SteeringAngle           #本车方向盘转角


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','V_VehSpdX','V_VehSpdY','V_VehAccelX','V_VehAccelY','V_VehPosYaw','V_VehPosX','V_VehPosY','V_VehPosRoll','V_VehPosPitch','GearLevPos']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,V_VehSpdX,V_VehSpdY,V_VehAccelX,V_VehAccelY,V_VehPosYaw,V_VehPosX,V_VehPosY,V_VehPosRoll,V_VehPosPitch,GearLevPos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Vehicle_Feedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.V_VehSpdX is None:
        self.V_VehSpdX = 0.
      if self.V_VehSpdY is None:
        self.V_VehSpdY = 0.
      if self.V_VehAccelX is None:
        self.V_VehAccelX = 0.
      if self.V_VehAccelY is None:
        self.V_VehAccelY = 0.
      if self.V_VehPosYaw is None:
        self.V_VehPosYaw = 0.
      if self.V_VehPosX is None:
        self.V_VehPosX = 0.
      if self.V_VehPosY is None:
        self.V_VehPosY = 0.
      if self.V_VehPosRoll is None:
        self.V_VehPosRoll = 0.
      if self.V_VehPosPitch is None:
        self.V_VehPosPitch = 0.
      if self.GearLevPos is None:
        self.GearLevPos = 0
    else:
      self.header = std_msgs.msg.Header()
      self.V_VehSpdX = 0.
      self.V_VehSpdY = 0.
      self.V_VehAccelX = 0.
      self.V_VehAccelY = 0.
      self.V_VehPosYaw = 0.
      self.V_VehPosX = 0.
      self.V_VehPosY = 0.
      self.V_VehPosRoll = 0.
      self.V_VehPosPitch = 0.
      self.GearLevPos = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9fI().pack(_x.V_VehSpdX, _x.V_VehSpdY, _x.V_VehAccelX, _x.V_VehAccelY, _x.V_VehPosYaw, _x.V_VehPosX, _x.V_VehPosY, _x.V_VehPosRoll, _x.V_VehPosPitch, _x.GearLevPos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.V_VehSpdX, _x.V_VehSpdY, _x.V_VehAccelX, _x.V_VehAccelY, _x.V_VehPosYaw, _x.V_VehPosX, _x.V_VehPosY, _x.V_VehPosRoll, _x.V_VehPosPitch, _x.GearLevPos,) = _get_struct_9fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9fI().pack(_x.V_VehSpdX, _x.V_VehSpdY, _x.V_VehAccelX, _x.V_VehAccelY, _x.V_VehPosYaw, _x.V_VehPosX, _x.V_VehPosY, _x.V_VehPosRoll, _x.V_VehPosPitch, _x.GearLevPos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.V_VehSpdX, _x.V_VehSpdY, _x.V_VehAccelX, _x.V_VehAccelY, _x.V_VehPosYaw, _x.V_VehPosX, _x.V_VehPosY, _x.V_VehPosRoll, _x.V_VehPosPitch, _x.GearLevPos,) = _get_struct_9fI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9fI = None
def _get_struct_9fI():
    global _struct_9fI
    if _struct_9fI is None:
        _struct_9fI = struct.Struct("<9fI")
    return _struct_9fI
